# Generated by Django 4.1 on 2022-09-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allevents",
            name="other_ids",
            field=models.TextField(blank=True, null=True),
        ),
    ]
