# Generated by Django 4.1 on 2022-09-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_allevents_usershare1_allevents_usershare2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allevents",
            name="updated",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
